import SwiftUI
import shared

func greet() -> String {
    Test().testBlockBody(int: 1)
    Test().testBlockBody(int: 2)
    Test().testBlockBody(int: 3)
    Test().testInline()
    Test().testUnit()
    return "Hello MMP, you can see some debug info generated by Kotlin Compiler Plugin"
}

struct ContentView: View {
    var body: some View {
        Text(greet())
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
